# -*- coding: utf-8 -*-
"""
/***************************************************************************
 shortpath
                                 A QGIS plugin
 Find shortest path between points based on line (network) layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-21
        copyright            : (C) 2021 by Revaz Gviniashvili
        email                : rewaza@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load shortpath class from file shortpath.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .short_path import shortpath
    return shortpath(iface)
